### ISSUE TITLE
Screen shots of scripts

### ISSUE THREAD

**Issue by boris-ny** [boris-ny/Group7_gcs-2#1]
![problem 5](https://user-images.githubusercontent.com/113375045/195604416-8b27f01c-a702-4f3e-aaad-c55d62c61130.jpg)
![problem 1](https://user-images.githubusercontent.com/113375045/195604425-8bfd78ac-8d53-4938-9b84-2dffb90bffcc.jpg)
![problem 2](https://user-images.githubusercontent.com/113375045/195604429-7b0f3df2-134f-426c-aed8-880dcf520457.jpg)
![problem 3](https://user-images.githubusercontent.com/113375045/195604432-1a1b87a8-124c-46ed-aa18-762df81b66e2.jpg)

**Comment by jefftrojan** [comment]
Nice job Boris
